export const DECKS = {
	ADD: "ADD_DECK",
	LOAD: "DECK_LOAD",
	REMOVE: "DECK_REMOVE",
	LOAD_SUCCESS: "DECK_LOAD_SUCCESS",
	LOAD_FAIL: "DECK_LOAD_FAIL"
};

export const CARDS = {
	ADD: "CARD_DECK",
	LOAD: "CARD_LOAD",
	REMOVE: "CARD_REMOVE",
	LOAD_SUCCESS: "CARD_LOAD_SUCCESS",
	LOAD_FAIL: "CARD_LOAD_FAIL"
};

export const QUIZ = {
	CORRECT: "QUIZ_CORRECT",
	INCORRECT: "QUIZ_INCORRECT",
	RESET: "QUIZ_RESET"
};
